services:
  frontend:
    build:
      context: ./reserva-de-restaurante-front  # Nome correto da pasta frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - API_URL=http://backend:8080/api
    depends_on:
      - backend

  backend:
    image: reservas-restaurantes
    build:
      context: ./reserva-restaurantes  # Nome correto da pasta backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
